# Generated by Django 5.2.3 on 2025-06-25 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competitoranalysis",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="competitor_analysis",
                to="app.products",
            ),
        ),
        migrations.AlterField(
            model_name="productanalysis",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_analysis",
                to="app.products",
            ),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_review",
                to="app.products",
            ),
        ),
        migrations.CreateModel(
            name="Distributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(null=True)),
                ("address", models.TextField(null=True)),
                ("contact", models.TextField(null=True)),
                ("email", models.TextField(null=True)),
                ("website", models.TextField(null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_analysis",
                        to="app.products",
                    ),
                ),
            ],
            options={
                "db_table": "distributor",
            },
        ),
    ]
